/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discord.vban.bot.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
